<a href="https://colab.research.google.com/github/madan-genai/machine-learning/blob/main/Bidirectional_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("/content/FA-KES-Dataset.csv", encoding='latin1')

In [4]:
df.head()

,unit_id,article_title,article_content,source,date,location,labels
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib,0
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs,0
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo,0
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo,0
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo,0

In [6]:
df.isnull().sum()

unit_id            0
article_title      0
article_content    0
source             0
date               0
location           0
labels             0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   unit_id          804 non-null    int64
 1   article_title    804 non-null    object
 2   article_content  804 non-null    object
 3   source           804 non-null    object
 4   date             804 non-null    object
 5   location         804 non-null    object
 6   labels           804 non-null    int64
dtypes: int64(2), object(5)
memory usage: 44.1+ KB

In [8]:
df.describe()

            unit_id      labels
count  8.040000e+02  804.000000
mean   1.936024e+09    0.529851
std    1.876968e+07    0.499419
min    1.914948e+09    0.000000
25%    1.923848e+09    0.000000
50%    1.924058e+09    1.000000
75%    1.962496e+09    1.000000
max    1.965511e+09    1.000000

In [9]:
df.shape

(804, 7)

In [10]:
df=df.dropna()

In [11]:
df.head()

,unit_id,article_title,article_content,source,date,location,labels
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib,0
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs,0
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo,0
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo,0
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo,0

In [12]:
X=df.drop("labels",axis=1)

In [13]:
y=df["labels"]

In [20]:
import tensorflow as tf

In [21]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [22]:
vocab_size=5000

In [23]:
messages=X.copy()

In [24]:
messages.head(5)

,unit_id,article_title,article_content,source,date,location
0,1914947530,Syria attack symptoms consistent with nerve ag...,Wed 05 Apr 2017 Syria attack symptoms consiste...,nna,4/5/2017,idlib
1,1914947532,Homs governor says U.S. attack caused deaths b...,Fri 07 Apr 2017 at 0914 Homs governor says U.S...,nna,4/7/2017,homs
2,1914947533,Death toll from Aleppo bomb attack at least 112,Sun 16 Apr 2017 Death toll from Aleppo bomb at...,nna,4/16/2017,aleppo
3,1914947534,Aleppo bomb blast kills six Syrian state TV,Wed 19 Apr 2017 Aleppo bomb blast kills six Sy...,nna,4/19/2017,aleppo
4,1914947535,29 Syria Rebels Dead in Fighting for Key Alepp...,Sun 10 Jul 2016 29 Syria Rebels Dead in Fighti...,nna,7/10/2016,aleppo

In [25]:
import nltk
import re
from nltk.corpus import stopwords

In [26]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [27]:
messages.reset_index(inplace=True)

In [30]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
for i in range(0,len(messages)):
  print(i)
  review = re.sub('[^a-zA-Z]', ' ', messages['article_title'][i])
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if not word in stopwords.words("english")]
  review = " ".join(review)
  corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803

In [32]:
corpus

['syria attack symptom consist nerv agent use',
 'hom governor say u attack caus death doesnt see big human loss',
 'death toll aleppo bomb attack least',
 'aleppo bomb blast kill six syrian state tv',
 'syria rebel dead fight key aleppo road',
 'suicid bomb kill least northeast syria',
 'dead heavi u raid syria stronghold',
 'suicid bomber kill assad clan hometown',
 'explos rock town damascu',
 'damascu explos due rocket bomb',
 'syrian regim step aerial assault douma',
 'hizballah lead regim offens southern syria',
 'syrian opposit remain divid',
 'video show murder syrian activist',
 'syria nusra front stage deadli suicid bomb aleppo',
 'regim troop thwart rebel attack syria aleppo',
 'ahrar al sham leader kill syria',
 'barrel bomb kill town syria',
 'rebel advanc north western syria',
 'isra strike syrian town kill pro regim fighter',
 'syria armi plane crash rebel held town',
 'syrian regim reveng attack kill score qalamoun',
 'chemic massacr idlib defi world',
 'bu bomb mark end tragic evacu deal syria',
 'six kill aleppo bomb evacu syrian town resum',
 'kill suspect ga attack syria idlib',
 'msf syrian regim use chemic weapon hama',
 'toxic ga drop syrian town russian helicopt shot',
 'syrian opposit spark aleppo front reliev north fraction',
 'dozen kill intern coalit airstrik manbij',
 'thirti kill syrian strike damascan suburb town',
 'russian syrian regim use intern ban bomb attack aleppo',
 'syria kurdish islamist violenc kill al qaeda link fighter',
 'syrian armi advanc near aleppo',
 'monitor peopl execut forc loyal regim children',
 'suicid bomber kill assad clan hometown',
 'us led airstrik target isi stronghold raqqa',
 'assad regim launch oper latakia region attack syrian turkmen villag',
 'assad regim kill civilian aleppo monitor',
 'russian airstrik hit syrian opposit forc',
 'syrian warplan crash market northwest town ariha near turkish border kill wound dozen',
 'suicid bomb attack syria idlib mosqu kill senior nusra front leader',
 'civilian kill syria hasakeh motorbik bomber attack',
 'medic among least dead regim shell opposit held syrian town',
 'assad regim airstrik kill civilian syria aleppo',
 'coalit airstrik kill civilian daesh held villag syria manbij',
 'assad regim surround aleppo opposit group resist despit intens raid',
 'us jet kill least civilian syria',
 'fatal expect increas suicid blast syria',
 'us led air strike syria kill dozen civilian',
 'syrian opposit advanc key aleppo district',
 'two russian pilot kill syria daesh down chopper',
 'least dead bomb hit refuge camp syria idlib',
 'ga attack hit rebel held area aleppo report',
 'syrian regim forc drop vacuum bomb idlib',
 'chemic attack idlib draw intern condemn',
 'regim air strike kill syria rebel held region',
 'air strike kill least northwestern syria',
 'multipl daesh suicid bomber attack refuge camp syria',
 'air strike syria kill eight white helmet activist',
 'air strike hit hospit kill peopl idlib',
 'deadli bomb blast hit syria aleppo',
 'least kill bomb hit bu convoy syria',
 'suicid bomber kill syria hasakah',
 'bomb continu fall syria despit regim truce',
 'syrian rebel fighter kill suicid bomb attack',
 'score syrian rebel kill key aleppo road',
 'us led coalit raid kill score civilian syria',
 'dozen kill bombard rebel held aleppo',
 'seven children kill syria rebel held aleppo',
 'syria airstrik destroy idlib msf hospit leav dead',
 'dozen kill russian air raid held raqqa',
 'four kill suspect ga attack aleppo',
 'three women kill attend funer syria madaya',
 'violenc rage syria dozen kill',
 'civilian kill syria aleppo',
 'syrian regim bomb kurdish fighter second day',
 'barrel bomb attack kill children syria aleppo',
 'children kill syria hom napalm mortar round',
 'kill regim strike besieg hom neighbourhood',
 'dozen kill hospit damag strike hit northwest syria',
 'score kill ga attack rebel held syria town',
 'syrian regim airstrik kill civilian near damascu',
 'shell rebel bastion near syrian capit kill',
 'syrian airbas struck us missil what damag',
 'strike syria idlib kill includ five children',
 'sarin nerv ga use syria british scientist',
 'syria rebel battl break aleppo sieg',
 'syrian children kill west aleppo school attack',
 'idlib bomb deadliest school attack syria war',
 'student among score dead raid hit syria school',
 'two dead twenti injur syrian regim chlorin attack',
 'heavi syrian regim bomb idlib kill civilian',
 'russia say belgian strike kill six aleppo region',
 'hour bombard aleppo kill',
 'dozen kill car bomb attack syrian rebel',
 'airstrik continu rain east aleppo',
 'russia launch new crippl air raid aleppo',
 'eleven kill syrian regim control area aleppo',
 'air raid kill syrian held villag',
 'suicid attack syria wed kill',
 'suicid attack kurdish wed syria kill',
 'two kill qatar red crescent syria clinic bomb',
 'syrian refuge camp hit missil bomb',
 'aleppo score kill airstrik target un aid convoy',
 'first civilian kill aleppo sinc start ceasefir',
 'syrian children kill missil attack school',
 'five dead syria airstrik ahead plan ceasefir',
 'syria regim kill civilian hama airstrik',
 'hundr dead fresh airstrik hit syria aleppo',
 'deadli aleppo convoy attack threaten aid distribut syria',
 'four medic kill strike clinic near aleppo',
 'syrian civil defenc us russia regim attack aid convoy',
 'syrian regim repel rebel offens near aleppo kill',
 'syrian regim offens northern aleppo leav dead',
 'unicef confirm children among deir ez zor dead',
 'score civilian kill airstrik raqqa',
 'heavi regim loss islam state raqqa counteroffens',
 'three children kill regim airstrik hom',
 'four hizballah member kill fight syria',
 'dozen dead suspect russian strike idlib marketplac',
 'airstrik syria kill dozen start ramadan',
 'dozen syrian regim air raid rebel held aleppo',
 'syrian regim airstrik kill dozen around aleppo',
 'airstrik kill civilian syria safe zone monitor',
 'us led strike kill civilian syria raqqa',
 'deadli twin bomb hit damascu polic station',
 'russian airstrik kill score flee civilian deir az zor',
 'syrian regim airstrik idlib market kill children',
 'tripl suicid attack near damascu polic hq ministri',
 'rebel shell kill four civilian damascu monitor',
 'three white helmet worker six children kill syria air',
 'civilian kill relentless regim bomb besieg damascu',
 'syrian regim airstrik target besieg eastern ghouta deir az zor',
 'russian strike kill civilian syria deir az zour',
 'dead strike rebel held hospit syria',
 'aleppo bomb blast kill six syrian state',
 'dozen children dead syria evacue bomb',
 'death toll aleppo bu convoy bomb attack least observatori',
 'bomb syrian bu convoy kill wound dozen outsid aleppo',
 'death toll bomb attack syria evacue hit monitor',
 'dead clash islamist milit near damascu monitor',
 'us back syrian fighter press gunmen north',
 'strike kill includ children syria idlib monitor',
 'one dead raid syria chemic attack town monitor',
 'dead suspect syria chemic attack new toll',
 'shell rebel bastion near syria capit kill monitor',
 'suspect ga attack syria rebel held idlib kill least observatori',
 'barrel bomb attack kill children syria aleppo monitor',
 'syria regim pound kurdish posit second day',
 'syrian rebel kill group suicid blast',
 'warplan pound syria idlib battl rage aleppo',
 'rebel fire syria aleppo kill state media',
 'air raid kill near syria hospit monitor',
 'barrel bomb kill least civilian syria aleppo monitor',
 'civilian dead air strike syria rebel town monitor',
 'syria regim bomb kill rebel held aleppo monitor',
 'doubl bomb attack kill syrian kurdish citi state tv',
 'syrian state tv say kill car bomb northern syria',
 'aleppo rebel tunnel blast kill regim forc monitor',
 'us led strike kill civilian syria monitor',
 'coalit raid kill civilian stronghold syria monitor',
 'air raid kill civilian syria aleppo monitor',
 'air raid kill civilian east syria monitor',
 'air strike kill rebel held area syria aleppo monitor',
 'air strike kill includ children syria idlib monitor',
 'coalit air strike turkish armi kill group milit report',
 'rocket attack kill least syria aleppo',
 'motorbik bomber kill outsid bakeri syria hasakeh',
 'kill syria armi shell rebel town monitor',
 'medic among dead syria armi repris slain pilot',
 'syria air raid kill civilian monitor',
 'dead attack kurd held syria town monitor',
 'syria rebel rocket kill five children',
 'turkish air strike kill fighter syria monitor',
 'civilian dead syrian raid held villag monitor',
 'missil kill civilian syria aleppo monitor',
 'barrel bomb kill civilian town syria',
 'civilian kill regim air raid northern syria',
 'huge regim bomb kill held syria town monitor',
 'bomb rocket kill civilian syria aleppo monitor',
 'dead new islamist allianc attack syria aleppo monitor',
 'air strike syria kill least islam state fighter monitor',
 'syria regim air strike kill near damascu monitor',
 'syrian air strike kill peopl rebel rocket attack monitor',
 'syria strike kill rebel fire damascu monitor',
 'syria air strike kill monitor',
 'seven dead wound central damascu blast monitor',
 'syria fight kill islam state fighter monitor',
 'suicid bomber kill assad clan hometown',
 'syria forc execut children alleg rebel monitor',
 'jihadist kill clash syria kurd monitor',
 'suicid bomber kill six syria restaur report',
 'dead al qaeda attack syria kurd town',
 'dead air raid syria latakia provinc ngo',
 'syrian armi kill rebel east damascu monitor group',
 'bomb kill damascu suburb state tv',
 'least kill syrian weapon depot blast',
 'syria regim raid kill camp displac ngo',
 'attack syria oil field kill monitor',
 'syria air strike kill children women aleppo monitor',
 'syrian troop kill clash monitor',
 'syria regim bomb kill includ children',
 'twin blast kill kurdish fighter syria monitor',
 'us led strike syria kill jihadist overnight monitor',
 'us led raid syria kill jihadist civilian',
 'us strike kill qaeda fighter syria monitor',
 'us led strike hit qaeda syria well monitor',
 'us led strike syria kill jihadist monitor',
 'syria air strike kill includ children monitor',
 'jihadist kill fight syria kurd monitor',
 'syria air strike kill dozen rebel town monitor',
 'worker dig dead syria regim strike aleppo',
 'updat regim air raid kill near syria capit new toll',
 'american among jihadist kill syria raid ngo',
 'syria armi kill rebel daraa provinc ambush ngo',
 'syria bomb jihadist posit raqa second day',
 'kill syria daraa aleppo ngo',
 'air raid kill jihadist syria raqa ngo',
 'syria troop kill least jihadist near lebanon monitor',
 'syria air strike jihadist camp kill new toll',
 'syria troop kill jihadist advanc monitor',
 'syria air raid kill islam state milit monitor',
 'russian strike kill civilian syria deir ezzor monitor',
 'car bomb kill eastern syria state media',
 'least kill air strike syrian market town observatori',
 'air raid kill civilian north syria town monitor',
 'bodi civilian found syrian town taken group',
 'rebel shell kill four civilian damascu monitor',
 'least dead syria market air strike monitor',
 'russia strike kill group fighter foreign mercenari syria',
 'monitor kill missil strike eastern syria citi',
 'us led strike kill civilian syria raqa monitor',
 'least kill north syria aleppo monitor',
 'russia regim strike kill east syria monitor',
 'civilian kill raid syria group bastion raqa monitor',
 'syria rebel kill aleppo assault captur villag monitor',
 'air strike syria idlib kill monitor',
 'civilian dead air strike market east syria monitor',
 'syria regim raid aleppo kill civilian monitor',
 'updat syria regim strike near aleppo civil defenc',
 'suicid bomber kill one syria regim stronghold state tv',
 'children among dead syria regim bomb civil defenc',
 'opposit minist among dead syria car bomb rebel',
 'civilian kill syria aid convoy attack red cross',
 'russia say syrian troop kill us led strike',
 'kill raid syria idlib monitor',
 'new strike kill least civilian syria aleppo monitor',
 'syrian armi say rebel bombard aleppo kill three day',
 'dozen civilian dead rebel assault aleppo',
 'rebel aleppo attack putin cautiou new russian raid',
 'rebel fire kill aleppo schoolchildren state media',
 'syria monitor say air strike kill school rebel held idlib',
 'group group land mine kill wound dozen syrian town',
 'dead heavi bombard syria idlib monitor',
 'air raid kill least civilian syria aleppo monitor',
 'turkish militari say group milit kill northern syria',
 'blast syria turkey border kill rebel monitor',
 'suicid attack syria wed kill medic sourc',
 'isil crucifi men syria aleppo ngo',
 'least syrian soldier kill isra raid ngo',
 'jihadist execut three syria rebel offic monitor',
 'car bomb kill least syria hama state media region world ahram onlin',
 'syria air raid displac person camp kill ngo region world ahram onlin',
 'dead syria barrel bomb attack aleppo',
 'syria rebel infight kill fighter day region world ahram onlin',
 'car bomb syria hom kill governor region world ahram onlin',
 'kill syria rebel shell assad elect ralli monitor region world ahram onlin',
 'syrian armi missil kill includ kid region world ahram onlin',
 'bomb syria idlib kill govern fighter monitor group region world ahram onlin',
 'children among dead syria car bomb state media region world ahram onlin',
 'car bomb rocket fire kill syria hom governor region world ahram onlin',
 'mortar fire damascu kill wound state media region world ahram onlin',
 'dead rebel fire regim part aleppo ngo region world ahram onlin',
 'dead two day clash syria daraa monitor region world ahram onlin',
 'air raid kill syria market monitor region world ahram onlin',
 'air strike kill dozen syria aleppo monitor group region world ahram onlin',
 'twin car bomb kill syria hom state media region world ahram onlin',
 'rebel dead syria prematur car bomb blast ngo region world ahram onlin',
 'mortar fire kill two damascu opera hous state media region world ahram onlin',
 'syria rebel jihadist kill ngo region world ahram onlin',
 'car bomb kill six syria hom ngo region world ahram onlin',
 'car bomb blast kill syria hom ngo region world ahram onlin',
 'five dead blast secur hq central syria ngo region world ahram onlin',
 'isra attack syria militari camp kill three jordan time',
 'dozen dead car bomb hit syria evacue jordan time',
 'strike kill near syria daesh held raqqa monitor jordan time',
 'outrag syria chemic attack kill dozen rebel held town jordan time',
 'five dead russian militari helicopt down syria jordan time',
 'dozen dead warplan pound rebel held north syria jordan time',
 'dozen dead warplan pound rebel held north syria jordan time',
 'least kill north syria aleppo monitor jordan time',
 'massiv daesh bomb attack kill syrian kurdish citi jordan time',
 'syria regim advanc rebel aleppo monitor jordan time',
 'civilian kill regim air raid northern syria jordan time',
 'barrel bomb kill civilian daesh town syria jordan time',
 'syria regim air strike kill least monitor jordan time',
 'syria air strike kill least monitor jordan time',
 'syria regim air strike kill near damascu monitor jordan time',
 'massiv daesh bomb attack kill syrian kurdish citi jordan time',
 'least kill north syria aleppo monitor jordan time',
 'syria rebel kill aleppo assault captur villag monitor jordan time',
 'raid syria market kill hundr flee daesh bastion jordan time',
 'dead daesh counterattack syria regim forc jordan time',
 'syrian russian aircraft step bomb aleppo citi monitor jordan time',
 'syria air strike kill mostli children outsid school jordan time',
 'syrian govern push damascu rebel enclav kill least jordan time',
 'air strike kill syria truce zone monitor jordan time',
 'syria regim bombard kill schoolchildren besieg enclav jordan time',
 'russian strike kill flee civilian east syria monitor jordan time',
 'us led strike kill civilian syria raqqa monitor jordan time',
 'russia say kill extremist mercenari syria claim shishani death jordan time',
 'nation news agenc damascu explos due rocket bomb',
 'nation news agenc blast syria hom kill children',
 'nation news agenc coalit raid kill isil fighter',
 'least kill bomb hit bu convoy syria',
 'us led air strike syria kill dozen civilian',
 'two russian pilot kill syria daesh down chopper',
 'us jet kill least civilian syria',
 'russian strike kill aleppo',
 'syrian russian air strike kill civilian idlib',
 'syrian russian air strike kill citi ashara',
 'suicid attack near shia shrine kill syrian observatori',
 'russian syrian strike kill civilian',
 'us russia broker syria truce end',
 'air strike syria kill least peopl',
 'string bomb blast kill least syria',
 'heavi air strike hit opposit held part aleppo',
 'unicef say schoolchildren six teacher kill syria raid',
 'russian syrian regim strike kill aleppo',
 'car bomb syria kill least near turkish border',
 'russian jet resum airstrik aleppo',
 'suicid bomb kill syria turkey border',
 'suicid bomber target syrian wed kill',
 'car bomb attack kill least syria war monitor say',
 'air strike kill dozen insid syria de escal zone',
 'least seven children die regim shell rebel held area syria',
 'least civilian kill russian regim air strike syria',
 'russia air strike kill least civilian syria monitor',
 'least dead suicid bomb hit damascu',
 'unidentifi air strike kill least eight hezbollah fighter syria',
 'least kill dozen injur twin bomb target syria qamishli near turkish border daili sabah',
 'air strike syrian hospit kill monitor group say daili sabah',
 'civilian kill russian air strike syria aleppo daili sabah',
 'russian airstrik target civilian syria idlib kill daili sabah',
 'daesh russia syrian regim target opposit daili sabah',
 'syrian warplan pound idlib leav dead daili sabah',
 'assad regim helicopt kill peopl barrel bomb aleppo daili sabah',
 'syria use chemic weapon turkey offer remedi lnur evik daili sabah',
 'least civilian dead toxic ga attack syria idlib',
 'russian airstrik hit syrian opposit forc',
 'opposit forc claim fighter kill other injur russian airstrik syria idlib',
 'russian strike kill civilian syria idlib monitor',
 'bomb kill woman wound syria hom',
 'daesh terrorist kill men syria deir el zour daili sabah',
 'us coalit airstrik kill civilian east syria',
 'airstrik northern eastern syria kill civilian activist',
 'least dead blast target evacu convoy strand near aleppo',
 'us led coalit airstrik kill partner forc pentagon say',
 'civilian kill injur assad regim airstrik syria idlib',
 'assad regim target civilian hom airstrik',
 'least white helmet rescuer kill airstrik syria hama',
 'airstrik assad regim warplan kill syria idlib destroy mosqu hama',
 'assad regim kill least refuge camp',
 'isi recaptur syrian ga field kill monitor group say',
 'least die barrel bomb attack syrian regim warplan',
 'kurdish fighter kill twin blast syria',
 'us led raid kill isi milit overnight monitor say',
 'school bomb kill children syria monitor',
 'terrorist kill n syria turkish artilleri coalit jet pound daesh target daili sabah',
 'regim russia air strike kill idlib strike continu pound road death aleppo',
 'daesh claim respons bomb near damascu least dead',
 'least kill dozen injur twin bomb target syria qamishli near turkish border',
 'coalit airstrik kill civilian daesh held villag syria manbij',
 'civilian kill syria hasakeh motorbik bomber attack',
 'assad regim airstrik kill civilian syria aleppo',
 'children kill airstrik eastern syria latest round russian syrian bomb unicef',
 'kill injur airstrik area near hospit marketplac syria aleppo',
 'civilian kill russian airstrik syria',
 'syrian regim bomb kill civilian aleppo region',
 'turkish militari kill daesh terrorist syria',
 'children teacher kill russian syrian airstrik near school idlib',
 'daesh mine kill wound dozen ypg held manbij hrw say',
 'aleppo airstrik kill peopl opposit held area',
 'kill injur russian air strike syria idlib',

In [35]:
one_hot_resp=[one_hot(word,vocab_size)for word in corpus]
one_hot_resp

[[4119, 3271, 2011, 4469, 3310, 1297, 1008],
 [1888, 4023, 867, 2674, 3271, 459, 1043, 4762, 716, 2097, 580, 2438],
 [1043, 1942, 590, 4811, 3271, 1582],
 [590, 4811, 2128, 1823, 1272, 3692, 4667, 1324],
 [4119, 3907, 3913, 1313, 3751, 590, 2898],
 [78, 4811, 1823, 1582, 1632, 4119],
 [3913, 2603, 2674, 4129, 4119, 4221],
 [78, 2979, 1823, 4083, 1826, 1863],
 [1206, 3429, 4463, 3859],
 [3859, 1206, 1662, 4346, 4811],
 [3692, 4110, 229, 4230, 1578, 3455],
 [904, 3275, 4110, 4580, 2533, 4119],
 [3692, 4958, 4136, 3254],
 [1142, 624, 2867, 3692, 4527],
 [4119, 242, 1408, 1640, 3446, 78, 4811, 590],
 [4110, 1424, 4268, 3907, 3271, 4119, 590],
 [2117, 4336, 2307, 3959, 1823, 4119],
 [3053, 4811, 1823, 4463, 4119],
 [3907, 3765, 1231, 3036, 4119],
 [2505, 2462, 3692, 4463, 1823, 1017, 4110, 2205],
 [4119, 3675, 1082, 4763, 3907, 2651, 4463],
 [3692, 4110, 2762, 3271, 1823, 3434, 2514],
 [1522, 723, 3038, 1043, 2882],
 [3377, 4811, 476, 4054, 749, 486, 4694, 4119],
 [1272, 1823, 590, 4811, 486, 3692, 4463, 2350],
 [1823, 975, 908, 3271, 4119, 3038],
 [4268, 3692, 4110, 1008, 1522, 639, 4949],
 [2678, 908, 4953, 3692, 4463, 3208, 313, 1429],
 [3692, 4958, 2887, 590, 1408, 2967, 1231, 4866],
 [3311, 1823, 2164, 1859, 1335, 3766],
 [3665, 1823, 3692, 2462, 3355, 4759, 4463],
 [3208, 3692, 4110, 1008, 2164, 2786, 4811, 3271, 590],
 [4119, 2146, 4988, 819, 1823, 4336, 4353, 3875, 2205],
 [3692, 3675, 3765, 2566, 590],
 [3143, 1576, 2865, 2289, 4055, 4110, 907],
 [78, 2979, 1823, 4083, 1826, 1863],
 [2186, 4286, 1335, 670, 2766, 4221, 1645],
 [4083, 4110, 1807, 2848, 4009, 1221, 3271, 3692, 28, 1558],
 [4083, 4110, 1823, 3205, 590, 3143],
 [3208, 1335, 3871, 3692, 4958, 2289],
 [3692,
  2673,
  4763,
  3310,
  1892,
  4463,
  4772,
  2566,
  2380,
  2746,
  1823,
  1554,
  3311],
 [78, 4811, 3271, 4119, 3038, 2881, 1823, 2991, 242, 1408, 3959],
 [3205, 1823, 4119, 2, 3505, 2979, 3271],
 [2103, 4141, 1582, 3913, 4110, 194, 4958, 2651, 3692, 4463],
 [4083, 4110, 1335, 1823, 3205, 4119, 590],
 [1859, 1335, 1823, 3205, 1713, 2651, 1558, 4119, 3766],
 [4083, 4110, 4264, 590, 4958, 3069, 3901, 2251, 1818, 4129],
 [2186, 2537, 1823, 1582, 3205, 4119],
 [781, 1716, 1543, 78, 2128, 4119],
 [2186, 4286, 2082, 2462, 4119, 1823, 3311, 3205],
 [3692, 4958, 3765, 3751, 590, 4539],
 [3877, 3208, 2633, 1823, 4119, 1713, 1531, 2236],
 [1582, 3913, 4811, 3871, 1817, 2117, 4119, 3038],
 [908, 3271, 3871, 3907, 2651, 4120, 590, 1334],
 [3692, 4110, 2289, 4953, 2203, 4811, 3038],
 [1522, 3271, 3038, 2111, 2164, 1514],
 [4110, 2082, 2462, 1823, 4119, 3907, 2651, 1221],
 [2082, 2462, 1823, 1582, 3078, 4119],
 [2592, 1713, 78, 2979, 3271, 1817, 2117, 4119],
 [2082, 2462, 4119, 1823, 2457, 3108, 4744, 4527],
 [2082, 2462, 3871, 2960, 1823, 1576, 3038],
 [3446, 4811, 2128, 3871, 4119, 590],
 [1582, 1823, 4811, 3871, 3377, 4433, 4119],
 [78, 2979, 1823, 4119, 2433],
 [4811, 3882, 2583, 4119, 2251, 4110, 2014],
 [3692, 3907, 2205, 1823, 78, 4811, 3271],
 [3434, 3692, 3907, 1823, 3751, 590, 2898],
 [2186, 4286, 1859, 4129, 1823, 3434, 3205, 4119],
 [3311, 1823, 281, 3907, 2651, 590],
 [2787, 907, 1823, 4119, 3907, 2651, 590],
 [4119, 1335, 4324, 3038, 4268, 2960, 3089, 3913],
 [3311, 1823, 3208, 2082, 4129, 2651, 1645],
 [1984, 1823, 975, 908, 3271, 590],
 [1510, 1584, 1823, 288, 1765, 4119, 4760],
 [819, 1922, 4119, 3311, 1823],
 [3205, 1823, 4119, 590],
 [3692, 4110, 4811, 2146, 2205, 3134, 1929],
 [3053, 4811, 3271, 1823, 907, 4119, 590],
 [907, 1823, 4119, 1888, 943, 3244, 650],
 [1823, 4110, 2462, 3539, 1888, 715],
 [3311, 1823, 2960, 314, 2462, 3871, 1892, 4119],
 [3434, 1823, 908, 3271, 3907, 2651, 4119, 4463],
 [3692, 4110, 1335, 1823, 3205, 2566, 3859],
 [194, 3907, 1921, 2566, 3692, 280, 1823],
 [3692, 2002, 2745, 2186, 51, 4486, 314],
 [2462, 4119, 3038, 1823, 3275, 2066, 907],
 [2202, 3310, 908, 1008, 4119, 2699, 3602],
 [4119, 3907, 1299, 750, 590, 608],
 [3692, 907, 1823, 4503, 590, 3234, 3271],
 [3038, 4811, 3960, 3234, 3271, 4119, 3075],
 [1701, 4141, 3434, 3913, 4129, 3871, 4119, 3234],
 [3877, 3913, 3260, 4751, 3692, 4110, 179, 3271],
 [2603, 3692, 4110, 4811, 3038, 1823, 3205],
 [4987, 867, 2093, 2462, 1823, 1272, 590, 1221],
 [453, 281, 590, 1823],
 [3311, 1823, 4746, 4811, 3271, 3692, 3907],
 [1335, 3882, 398, 680, 590],
 [4987, 1807, 2046, 4908, 2082, 4129, 590],
 [3367, 1823, 3692, 4110, 2626, 4120, 590],
 [2082, 4129, 1823, 3692, 2651, 1558],
 [78, 3271, 4119, 4385, 1823],
 [78, 3271, 2146, 4385, 4119, 1823],
 [3877, 1823, 307, 874, 3072, 4119, 1508, 4811],
 [3692, 1817, 2117, 3871, 51, 4811],
 [590, 3434, 1823, 1335, 670, 1296, 3093, 4433],
 [2942, 3205, 1823, 590, 663, 4785, 4122],
 [3692, 907, 1823, 51, 3271, 3234],
 [2066, 3913, 4119, 1335, 4397, 4713, 4122],
 [4119, 4110, 1823, 3205, 4949, 1335],
 [1189, 3913, 1255, 1335, 3871, 4119, 590],
 [3446, 590, 4433, 3271, 4811, 3093, 1188, 4119],
 [1984, 2103, 1823, 2462, 1508, 2566, 590],
 [3692, 4366, 1483, 2186, 4987, 4110, 3271, 3093, 4433],
 [3692, 4110, 1309, 3907, 4580, 2566, 590, 1823],
 [3692, 4110, 4580, 1195, 590, 3089, 3913],
 [371, 3664, 907, 4141, 3666, 2839, 66, 3913],
 [3434, 3205, 1823, 1335, 1645],
 [2603, 4110, 2438, 4387, 4667, 1645, 3124],
 [1510, 907, 1823, 4110, 1335, 1888],
 [1984, 904, 1018, 1823, 1313, 4119],
 [3311, 3913, 975, 3208, 2462, 3038, 659],
 [1335, 4119, 1823, 3311, 4785, 2125],
 [3311, 3692, 4110, 2082, 4129, 3907, 2651, 590],
 [3692, 4110, 1335, 1823, 3311, 3978, 590],
 [1335, 1823, 3205, 4119, 2427, 112, 3143],
 [2186, 4286, 2462, 1823, 3205, 4119, 1645],
 [3446, 3760, 4811, 3871, 3859, 2046, 4720],
 [3208, 1335, 1823, 3434, 2391, 3205, 3666, 2132, 66],
 [3692, 4110, 1335, 3038, 3310, 1823, 907],
 [884, 78, 3271, 2566, 3859, 2046, 629, 19],
 [3907, 194, 1823, 1984, 3205, 3859, 3143],
 [1510, 3108, 4744, 2351, 1272, 907, 1823, 4119, 2082],
 [3205, 1823, 2485, 4110, 4811, 3539, 3859],
 [3692, 4110, 1335, 670, 3539, 3786, 3433, 3666, 2132, 66],
 [3208, 2462, 1823, 3205, 4119, 3666, 2132, 2586],
 [3913, 2462, 3907, 2651, 2960, 4119],
 [590, 4811, 2128, 1823, 1272, 3692, 4667],
 [3311, 907, 3913, 4119, 2941, 4811],
 [1043, 1942, 590, 3377, 4433, 4811, 3271, 1582, 1858],
 [4811, 3692, 3377, 4433, 1823, 1554, 3311, 496, 590],
 [1043, 1942, 4811, 3271, 4119, 2941, 3871, 3143],
 [3913, 2285, 4988, 2423, 2566, 3859, 3143],
 [2186, 1853, 3692, 2205, 2810, 4428, 1231],
 [2462, 1823, 3275, 907, 4119, 3038, 3143],
 [604, 3913, 4129, 4119, 1522, 3271, 4463, 3143],
 [3913, 975, 4119, 1522, 3271, 2046, 1942],
 [194, 3907, 1921, 2566, 4119, 280, 1823, 3143],
 [975, 908, 3271, 4119, 3907, 2651, 3038, 1823, 1582, 1858],
 [3053, 4811, 3271, 1823, 907, 4119, 590, 3143],
 [4119, 4110, 4210, 2146, 2566, 3134, 1929],
 [3692, 3907, 1823, 3069, 78, 2128],
 [2673, 4210, 4119, 3038, 1299, 1922, 590],
 [3907, 2686, 4119, 590, 1823, 4667, 2728],
 [2082, 4129, 1823, 2566, 4119, 2960, 3143],
 [3053, 4811, 1823, 1582, 3205, 4119, 590, 3143],
 [3205, 3913, 2082, 2462, 4119, 3907, 4463, 3143],
 [4119, 4110, 4811, 1823, 3907, 2651, 590, 3143],
 [3726, 4811, 3271, 1823, 3692, 2146, 1611, 4667, 1324],
 [3692, 4667, 1324, 867, 1823, 4746, 4811, 1195, 4119],
 [590, 3907, 2099, 2128, 1823, 4110, 2289, 3143],
 [2186, 4286, 2462, 1823, 3205, 4119, 3143],
 [1859, 4129, 1823, 3205, 4221, 4119, 3143],
 [2082, 4129, 1823, 3205, 4119, 590, 3143],
 [2082, 4129, 1823, 3205, 680, 4119, 3143],
 [2082, 2462, 1823, 3907, 2651, 4120, 4119, 590, 3143],
 [2082, 2462, 1823, 3275, 907, 4119, 3038, 3143],
 [1859, 2082, 2462, 2380, 3675, 1823, 3069, 2423, 1334],
 [4346, 3271, 1823, 1582, 4119, 590],
 [3505, 2979, 1823, 496, 3763, 4119, 2],
 [1823, 4119, 3675, 194, 3907, 4463, 3143],
 [2103, 4141, 3913, 4119, 3675, 1119, 466, 2633],
 [4119, 2082, 4129, 1823, 3205, 3143],
 [3913, 3271, 1522, 2651, 4119, 4463, 3143],
 [4119, 3907, 4346, 1823, 2066, 907],
 [2380, 2082, 2462, 1823, 2205, 4119, 3143],
 [3205, 3913, 3692, 4129, 2651, 1558, 3143],
 [51, 1823, 3205, 4119, 590, 3143],
 [3053, 4811, 1823, 3205, 4463, 4119],
 [3205, 1823, 4110, 2082, 4129, 1195, 4119],
 [1698, 4110, 4811, 1823, 2651, 4119, 4463, 3143],
 [4811, 4346, 1823, 3205, 4119, 590, 3143],
 [3913, 2046, 4988, 2262, 3271, 4119, 590, 3143],
 [2082, 2462, 4119, 1823, 1582, 4387, 4667, 2205, 3143],
 [4119, 4110, 2082, 2462, 1823, 2566, 3859, 3143],
 [3692, 2082, 2462, 1823, 1576, 3907, 4346, 3271, 3143],
 [4119, 2462, 1823, 3907, 2686, 3859, 3143],
 [4119, 2082, 2462, 1823, 3143],
 [2787, 3913, 1554, 1484, 3859, 2128, 3143],
 [4119, 1313, 1823, 4387, 4667, 2205, 3143],
 [78, 2979, 1823, 4083, 1826, 1863],
 [4119, 2289, 2865, 907, 189, 3907, 3143],
 [4521, 1823, 2285, 4119, 1522, 3143],
 [78, 2979, 1823, 1272, 4119, 4527, 1334],
 [3913, 4336, 4353, 3271, 4119, 1522, 4463],
 [3913, 2082, 4129, 4119, 4009, 1211, 674],
 [3692, 3675, 1823, 3907, 680, 3859, 3143, 3069],
 [4811, 1823, 3859, 4759, 4667, 1324],
 [1582, 1823, 3692, 639, 263, 2128],
 [4119, 4110, 4129, 1823, 2117, 1004, 674],
 [3271, 4119, 1454, 4467, 1823, 3143],
 [4119, 2082, 2462, 1823, 907, 1584, 590, 3143],
 [3692, 1424, 1823, 2285, 3143],
 [4119, 4110, 4811, 1823, 3275, 907],
 [3760, 2128, 1823, 2146, 2205, 4119, 3143],
 [2186, 4286, 2462, 4119, 1823, 4521, 865, 3143],
 [2186, 4286, 4129, 4119, 1823, 4521, 3205],
 [2186, 2462, 1823, 4353, 2205, 4119, 3143],
 [2186, 4286, 2462, 3871, 4353, 4119, 4166, 3143],
 [2186, 4286, 2462, 4119, 1823, 4521, 3143],
 [4119, 2082, 2462, 1823, 3275, 907, 3143],
 [4521, 1823, 1313, 4119, 1522, 3143],
 [4119, 2082, 2462, 1823, 3311, 3907, 4463, 3143],
 [2351, 815, 3913, 4119, 4110, 2462, 590],
 [3645, 4110, 2082, 4129, 1823, 2566, 4119, 280, 2046, 1942],
 [3273, 4141, 4521, 1823, 4119, 4129, 674],
 [4119, 3675, 1823, 3907, 1469, 1211, 1716, 674],
 [4119, 4811, 4521, 2566, 4667, 3134, 1929],
 [1823, 4119, 1469, 590, 674],
 [2082, 4129, 1823, 4521, 4119, 4667, 674],
 [4119, 1424, 1823, 1582, 4521, 2566, 4898, 3143],
 [4119, 2082, 2462, 4521, 2117, 1823, 2046, 1942],
 [4119, 1424, 1823, 4521, 3765, 3143],
 [4119, 2082, 4129, 1823, 4387, 4667, 2423, 3143],
 [3208, 2462, 1823, 3205, 4119, 3666, 2074, 3143],
 [4746, 4811, 1823, 3786, 4119, 4667, 2728],
 [1582, 1823, 2082, 2462, 3692, 3310, 4463, 1858],
 [2082, 4129, 1823, 3205, 1231, 4119, 4463, 3143],
 [837, 3205, 2179, 3692, 4463, 3519, 3069],
 [3907, 194, 1823, 1984, 3205, 3859, 3143],
 [1582, 3913, 4119, 3310, 2082, 2462, 3143],
 [4987, 2462, 1823, 3069, 2205, 3622, 4109, 4119],
 [3143, 1823, 51, 2462, 3786, 4119, 1611],
 [2186, 4286, 2462, 1823, 3205, 4119, 4667, 3143],
 [1582, 1823, 1231, 4119, 590, 3143],
 [4987, 4110, 2462, 1823, 680, 4119, 3143],
 [3205, 1823, 4129, 4119, 3069, 1921, 4667, 3143],
 [4119, 3907, 1823, 590, 1578, 4578, 1558, 3143],
 [2082, 2462, 4119, 3038, 1823, 3143],
 [3205, 3913, 2082, 2462, 3310, 680, 4119, 3143],
 [4119, 4110, 4129, 590, 1823, 3205, 3143],
 [3645, 4119, 4110, 2462, 2566, 590, 4366, 1483],
 [78, 2979, 1823, 604, 4119, 4110, 4221, 4667, 1324],
 [907, 4141, 3913, 4119, 4110, 4811, 4366, 1483],
 [4958, 4313, 4141, 3913, 4119, 4746, 4811, 3907],
 [3205, 1823, 4119, 3093, 4433, 3271, 874, 1355],
 [4987, 867, 3692, 1424, 1823, 2186, 4286, 2462],
 [1823, 4129, 4119, 3038, 3143],
 [2046, 2462, 1823, 1582, 3205, 4119, 590, 3143],
 [3692, 3675, 867, 3907, 281, 590, 1823, 1510, 1929],
 [3311, 3205, 3913, 3907, 1578, 590],
 [3907, 590, 3271, 3397, 3893, 2046, 3208, 4129],
 [3907, 2686, 1823, 590, 1021, 4667, 2728],
 [4119, 3143, 867, 2082, 2462, 1823, 3234, 3907, 2651, 3038],
 [3069, 3069, 1569, 4144, 1823, 1554, 3311, 3692, 4463],
 [3913, 2603, 281, 4119, 3038, 3143],
 [2082, 4129, 1823, 1582, 3205, 4119, 590, 3143],
 [2380, 648, 867, 3069, 2423, 1823, 1195, 4119],
 [2128, 4119, 4310, 2746, 1823, 3907, 3143],
 [78, 3271, 4119, 4385, 1823, 2103, 309],
 [4621, 3425, 2598, 4119, 590, 674],
 [1582, 3692, 1080, 1823, 2505, 4129, 674],
 [4521, 2865, 1510, 4119, 3907, 2356, 3143],
 [4746, 4811, 1823, 1582, 4119, 4949, 4667, 2728, 1221, 2882, 1769, 57],
 [4119, 2082, 4129, 1004, 4078, 2117, 1823, 674, 1221, 2882, 1769, 57],
 [3913, 4119, 3053, 4811, 3271, 590],
 [4119, 3907, 3941, 1823, 2205, 1929, 1221, 2882, 1769, 57],
 [4746, 4811, 4119, 1888, 1823, 4023, 1221, 2882, 1769, 57],
 [1823, 4119, 3907, 194, 4083, 2121, 4478, 3143, 1221, 2882, 1769, 57],
 [3692, 3675, 51, 1823, 3275, 2708, 1221, 2882, 1769, 57],
 [4811, 4119, 3038, 1823, 4552, 2205, 3143, 3069, 1221, 2882, 1769, 57],
 [907, 4141, 3913, 4119, 4746, 4811, 4667, 2728, 1221, 2882, 1769, 57],
 [4746, 4811, 4346, 2686, 1823, 4119, 1888, 4023, 1221, 2882, 1769, 57],
 [3244, 2686, 3859, 1823, 1554, 4667, 2728, 1221, 2882, 1769, 57],
 [3913, 3907, 2686, 4110, 459, 590, 674, 1221, 2882, 1769, 57],
 [3913, 3877, 1929, 2285, 4119, 1469, 3143, 1221, 2882, 1769, 57],
 [2082, 4129, 1823, 4119, 3310, 3143, 1221, 2882, 1769, 57],
 [2082, 2462, 1823, 3311, 4119, 590, 3143, 3069, 1221, 2882, 1769, 57],
 [3760, 4746, 4811, 1823, 4119, 1888, 4667, 2728, 1221, 2882, 1769, 57],
 [3907, 3913, 4119, 792, 4746, 4811, 2128, 674, 1221, 2882, 1769, 57],
 [3244, 2686, 1823, 3877, 3859, 1428, 3126, 4667, 2728, 1221, 2882, 1769, 57],
 [4119, 3907, 4521, 1823, 674, 1221, 2882, 1769, 57],
 [4746, 4811, 1823, 1272, 4119, 1888, 674, 1221, 2882, 1769, 57],
 [4746, 4811, 2128, 1823, 4119, 1888, 674, 1221, 2882, 1769, 57],
 [2066, 3913, 2128, 4595, 629, 1484, 4119, 674, 1221, 2882, 1769, 57],
 [2505, 3271, 4119, 648, 2117, 1823, 1510, 1972, 192],
 [3311, 3913, 4746, 4811, 3871, 4119, 2941, 1972, 192],
 [2462, 1823, 2566, 4119, 1713, 2651, 1645, 3143, 1972, 192],
 [217, 4119, 1522, 3271, 1823, 3311, 3907, 2651, 4463, 1972, 192],
 [2066, 3913, 3208, 648, 313, 1531, 4119, 1972, 192],
 [3311, 3913, 2673, 4210, 3907, 2651, 1231, 4119, 1972, 192],
 [3311, 3913, 2673, 4210, 3907, 2651, 1231, 4119, 1972, 192],
 [1582, 1823, 1231, 4119, 590, 3143, 1972, 192],
 [834, 1713, 4811, 3271, 1823, 3692, 2146, 1611, 1972, 192],
 [4119, 4110, 3765, 3907, 590, 3143, 1972, 192],
 [3205, 1823, 4110, 2082, 4129, 1195, 4119, 1972, 192],
 [3053, 4811, 1823, 3205, 1713, 4463, 4119, 1972, 192],
 [4119, 4110, 2082, 2462, 1823, 1582, 3143, 1972, 192],
 [4119, 2082, 2462, 1823, 1582, 3143, 1972, 192],
 [4119, 4110, 2082, 2462, 1823, 2566, 3859, 3143, 1972, 192],
 [834, 1713, 4811, 3271, 1823, 3692, 2146, 1611, 1972, 192],
 [1582, 1823, 1231, 4119, 590, 3143, 1972, 192],
 [4119, 3907, 1823, 590, 1578, 4578, 1558, 3143, 1972, 192],
 [4129, 4119, 3310, 1823, 1189, 2391, 1713, 1921, 1972, 192],
 [3913, 1713, 410, 4119, 4110, 2289, 1972, 192],
 [3692, 3208, 4173, 229, 4811, 590, 1611, 3143, 1972, 192],
 [4119, 2082, 2462, 1823, 3078, 907, 496, 3234, 1972, 192],
 [3692, 4552, 4028, 3859, 3907, 3617, 1823, 1582, 1972, 192],
 [2082, 2462, 1823, 4119, 2014, 112, 3143, 1972, 192],
 [4119, 4110, 281, 1823, 1021, 3539, 3617, 1972, 192],
 [3208, 2462, 1823, 2391, 3205, 680, 4119, 3143, 1972, 192],
 [2186, 4286, 2462, 1823, 3205, 4119, 1645, 3143, 1972, 192],
 [4987, 867, 1823, 2168, 4109, 4119, 4321, 4706, 1043, 1972, 192],
 [4999, 4139, 933, 3859, 1206, 1662, 4346, 4811],
 [4999, 4139, 933, 2128, 4119, 1888, 1823, 907],
 [4999, 4139, 933, 1859, 4129, 1823, 4621, 2205],
 [1582, 1823, 4811, 3871, 3377, 4433, 4119],
 [2186, 4286, 2082, 2462, 4119, 1823, 3311, 3205],
 [3877, 3208, 2633, 1823, 4119, 1713, 1531, 2236],
 [2186, 2537, 1823, 1582, 3205, 4119],
 [3208, 2462, 1823, 590],
 [3692, 3208, 2082, 2462, 1823, 3205, 3038],
 [3692, 3208, 2082, 2462, 1823, 1611, 3733],
 [78, 3271, 2566, 1983, 1711, 1823, 3692, 1858],
 [3208, 3692, 2462, 1823, 3205],
 [2186, 4987, 954, 4119, 2014, 4054],
 [2082, 2462, 4119, 1823, 1582, 1576],
 [4340, 4811, 2128, 1823, 1582, 4119],
 [2603, 2082, 2462, 3871, 4958, 2651, 459, 590],
 [371, 867, 1021, 1272, 1389, 1823, 4119, 4129],
 [3208, 3692, 4110, 2462, 1823, 590],
 [4746, 4811, 4119, 1823, 1582, 2566, 2380, 2746],
 [3208, 2537, 2350, 1335, 590],
 [78, 4811, 1823, 4119, 4310, 2746],
 [78, 2979, 670, 3692, 4385, 1823],
 [4746, 4811, 3271, 1823, 1582, 4119, 3075, 3143, 867],
 [2082, 2462, 1823, 3311, 303, 4119, 4743, 30, 112],
 [1582, 2787, 907, 4695, 4110, 194, 3907, 2651, 4120, 4119],
 [1582, 3205, 1823, 3208, 4110, 2082, 2462, 4119],
 [4987, 2082, 2462, 1823, 1582, 3205, 4119, 3143],
 [1582, 3913, 78, 4811, 3871, 3859],
 [1364, 2082, 2462, 1823, 1582, 2457, 2727, 2205, 4119],
 [1582,
  1823,
  3311,
  4751,
  3760,
  4811,
  670,
  4119,
  3678,
  2566,
  2380,
  2746,
  2773,
  3186],
 [2082, 2462, 3692, 2960, 1823, 3143, 3069, 867, 2773, 3186],
 [3205, 1823, 3208, 2082, 2462, 4119, 590, 2773, 3186],
 [3208, 1335, 670, 3205, 4119, 3038, 1823, 2773, 3186],
 [1713, 4987, 3692, 4110, 670, 4958, 2773, 3186],
 [3692, 2673, 4210, 3038, 3089, 3913, 2773, 3186],
 [4083, 4110, 313, 1823, 1576, 3053, 4811, 590, 2773, 3186],
 [4119, 1008, 1522, 639, 4310, 4014, 383, 2512, 1604, 2773, 3186],
 [1582, 3205, 3913, 2678, 908, 3271, 4119, 3038],
 [3208, 1335, 3871, 3692, 4958, 2289],
 [4958, 2289, 4321, 2205, 1823, 498, 4751, 3208, 1335, 4119, 3038],
 [3208, 2462, 1823, 3205, 4119, 3038, 3143],
 [4811, 1823, 3406, 1554, 4119, 1888],
 [1713, 4652, 1823, 2598, 4119, 3666, 3701, 2586, 2773, 3186],
 [2186, 1859, 1335, 1823, 3205, 680, 4119],
 [1335, 1195, 3786, 4119, 1823, 3205, 4527],
 [1582, 3913, 2128, 670, 486, 4433, 3076, 2566, 590],
 [2186, 4286, 1859, 1335, 1823, 4783, 2289, 4643, 867],
 [3205, 1823, 4751, 4083, 4110, 1335, 4119, 3038],
 [4083, 4110, 670, 3205, 1888, 1335],
 [1582, 3108, 4744, 2308, 1823, 1335, 4119, 4949],
 [1335, 4083, 4110, 2673, 1823, 4119, 3038, 4324, 2881, 4949],
 [4083, 4110, 1823, 1582, 1817, 2117],
 [2766, 2281, 3692, 908, 4467, 1823, 3143, 3069, 867],
 [1582, 4695, 3053, 4811, 3271, 3692, 4110, 2673],
 [2146, 2205, 1823, 3760, 2128, 4119],
 [2186, 4286, 4129, 1823, 2766, 2423, 865, 3143, 867],
 [3234, 4811, 1823, 907, 4119, 3143],
 [4652, 1823, 22, 4119, 2380, 1323, 1859, 2537, 4210, 1713, 670, 2773, 3186],
 [4110, 4987, 2082, 2462, 1823, 3038, 2462, 3882, 4210, 2898, 1043, 590],
 [1713, 4321, 1548, 4811, 2566, 3859, 1582, 3913],
 [1582, 1823, 3311, 4751, 3760, 4811, 670, 4119, 3678, 2566, 2380, 2746],
 [1859, 1335, 1823, 3205, 1713, 2651, 1558, 4119, 3766],
 [3205, 1823, 4119, 2, 3505, 2979, 3271],
 [4083, 4110, 1335, 1823, 3205, 4119, 590],
 [907, 1823, 1335, 3786, 4119, 2390, 650, 3208, 3692, 4811, 371],
 [1823, 4751, 1335, 4120, 2566, 2960, 659, 4119, 590],
 [3205, 1823, 3208, 1335, 4119],
 [3692, 4110, 4811, 1823, 3205, 590, 1221],
 [2380, 648, 1823, 1713, 4652, 4119],
 [907, 1389, 1823, 3208, 3692, 1335, 2566, 3234, 3038],
 [1713, 4144, 1823, 1554, 3311, 1342, 2651, 3766, 2968, 867],
 [590, 1335, 1823, 1576, 4958, 2651, 4120],
 [1823, 4751, 3208, 2082, 2462, 4119, 3038],
 [1043, 1942, 1150, 590, 2699, 1136, 45, 4987],
 [78, 3271, 4385, 4140, 4119, 1823, 4751],
 [1823, 78, 3271, 4119, 4385],
 [1904, 4958, 2205, 1823, 2285, 2518, 1195, 4119],
 [1582, 1823, 4110, 2462, 590, 1296, 3185, 4119],
 [4083, 4110, 2462, 1823, 3205, 4119, 590],
 [4083, 2082, 2462, 1823, 1582, 3205, 3275, 907, 4119, 590],
 [1335, 1508, 1823, 2103, 4119, 590],
 [2082, 2462, 1823, 3205, 1713, 2651, 4119, 4463, 3143],
 [3205, 1823, 4083, 4110, 4811, 2566, 3859],
 [4083, 4110, 1335, 1823, 1582, 3205, 4119, 3786, 3433],
 [1576, 3275, 907, 1823, 4083, 4110, 2566, 3859, 1296, 867],
 [1576, 1823, 498, 4751, 1713, 4746, 4811, 3786, 4119],
 [4110, 194, 1823, 3205, 3275, 907, 4119, 3859],
 [4110, 1335, 1823, 3205, 590, 4958, 2651, 4773],
 [1582, 1823, 884, 4811, 4119, 3859],
 [4613, 4336, 242, 4652, 2865, 4428, 2203, 2463, 1221, 1250],
 [3205, 1823, 4751, 590, 194, 3854],
 [3692, 2289, 4324, 4652, 1512, 2588, 2728],
 [1522, 3271, 4321, 2013, 4119],
 [2186, 4286, 1859, 1335, 1823, 3205, 1195, 4119],
 [4078, 1823, 498, 4751, 4652, 4346, 3271, 590, 1611],
 [1323, 3205, 907, 1823, 1335, 2186, 4286, 1859, 1645],
 [3205, 1823, 30, 281, 3038, 3678, 1510, 1929],
 [1675, 4083, 4811, 590, 3566, 2164, 3866, 234],
 [3205, 1823, 3053, 4811, 3271, 1660, 590],
 [3205, 1823, 4751, 4652, 4346, 3271, 590, 3666, 2074],
 [2766, 2865, 1510, 1576, 1645, 3666, 2074],
 [3205, 3913, 1859, 2462, 2566, 1645],

In [37]:
sent_length=20
embedded_docs=pad_sequences(one_hot_resp,padding='pre',maxlen=sent_length)

embedded_docs

array([[   0,    0,    0, ..., 3310, 1297, 1008],
       [   0,    0,    0, ..., 2097,  580, 2438],
       [   0,    0,    0, ..., 4811, 3271, 1582],
       ...,
       [   0,    0,    0, ..., 3692,  590, 4030],
       [   0,    0,    0, ..., 2236, 1429, 4119],
       [   0,    0,    0, ..., 4652, 3666, 2074]], dtype=int32)

In [47]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional, Input

embedding_feature_vectors = 40

model = Sequential()

model.add(Input(shape=(sent_length,)))

model.add(Embedding(input_dim=vocab_size,
                    output_dim=embedding_feature_vectors))

model.add(Bidirectional(LSTM(100)))

model.add(Dense(1, activation="sigmoid"))

model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 20, 40)         │       200,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_5 (Bidirectional) │ (None, 200)            │       112,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           201 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 313,001 (1.19 MB)

 Trainable params: 313,001 (1.19 MB)

 Non-trainable params: 0 (0.00 B)

In [48]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [49]:
## train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [51]:
## Model Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=32)

Epoch 1/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 5s 69ms/step - accuracy: 0.5172 - loss: 0.6940 - val_accuracy: 0.5564 - val_loss: 0.6914
Epoch 2/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 42ms/step - accuracy: 0.5083 - loss: 0.6916 - val_accuracy: 0.5564 - val_loss: 0.6882
Epoch 3/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - accuracy: 0.5136 - loss: 0.6857 - val_accuracy: 0.5376 - val_loss: 0.6901
Epoch 4/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.6537 - loss: 0.6579 - val_accuracy: 0.4925 - val_loss: 0.7145
Epoch 5/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 41ms/step - accuracy: 0.7828 - loss: 0.5714 - val_accuracy: 0.4850 - val_loss: 0.8701
Epoch 6/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - accuracy: 0.8176 - loss: 0.4257 - val_accuracy: 0.5038 - val_loss: 0.7812
Epoch 7/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.8477 - loss: 0.4119 - val_accuracy: 0.5075 - val_loss: 0.9661
Epoch 8/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - accuracy: 0.8454 - loss: 0.3465 - val_accuracy: 0.5038 - val_loss: 1.1140
Epoch 9/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 53ms/step - accuracy: 0.8766 - loss: 0.3012 - val_accuracy: 0.5113 - val_loss: 1.1279
Epoch 10/10
17/17 ━━━━━━━━━━━━━━━━━━━━ 1s 65ms/step - accuracy: 0.9031 - loss: 0.2837 - val_accuracy: 0.5188 - val_loss: 1.2472

In [52]:
y_pred=model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

In [53]:
import numpy as np

y_pred=np.where(y_pred>=0.5,1,0)

In [54]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[50, 68],
       [60, 88]])

In [55]:
print(accuracy_score(y_test,y_pred))

0.518796992481203